baseurl = "https://www.instant-dreams.org/"
languageCode = "en-ca"
title = "Rachel and Dean"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 4

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Rachel and Dean"
	description = "Wedding Plans"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**We are getting married!**<br /><br />We'd love for<br />you to join us<br />"
		# The icons will be shown if you enter your username
		twitter = "_instantdreams_"
		github = "instantdreams"
		gitlab = ""
		dribbble = ""
		facebook = "morpheus.dreaming"
		googleplus = ""
		flickr = ""
		linkedin = "deansmith"

		copyright = [
			"&copy; Instant Dreams",
			"Design: [HTML5 UP](//html5up.net)"
		]

	[params.about]
		hide  = false
		title = "Join us at our celebration"
		content = "Friends, family, we want you to be able to share in our special day - but we understand not everyone is local"

	[params.portfolio]
		hide  = false
		title = "The Plan"
		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "full/Boston.jpg"
			thumb = "thumb/Boston-Thumb.jpg"
			title = "Engagement"
			description = "We got engaged on Rachel's birthday in 2019"

		[[params.portfolio.gallery]]
			image = "full/PyramidLake.jpg"
			thumb = "thumb/PyramidLake-Thumb.jpg"
			title = "Save the Date"
			description = "We are planning on getting married on Dean's birthday in 2019"

		[[params.portfolio.gallery]]
			image = "full/DrivingtoJasper.jpg"
			thumb = "thumb/DrivingtoJasper-Thumb.jpg"
			title = "Travel to Jasper"
			description = "We will drive to Jasper on the Saturday before his birthday"

		[[params.portfolio.gallery]]
			image = "full/AthabascaDayUseArea.jpg"
			thumb = "thumb/AthabascaDayUseArea-Thumb.jpg"
			title = "The Ceremony"
			description = "We will be married at the edge of the beautiful Athabasca river"

		[[params.portfolio.gallery]]
			image = "full/JasperTownsite.jpg"
			thumb = "thumb/JasperTownsite-Thumb.jpg"
			title = "Reception"
			description = "Our reception location is still to be arranged!"

		[[params.portfolio.gallery]]
			image = "full/SomewhereInEngland.jpg"
			thumb = "thumb/SomewhereInEngland-Thumb.jpg"
			title = "Visit to England"
			description = "We will come to England in Spring 2021 to celebrate with you!"

	[params.recentposts]
#		hide  = false
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "RSVP"
		content = "Please let us know if you will be able to make it!"

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "52.993266,-118.0543234"
		address = [
			"Athabasca Day Use Area",
			"Jasper National Park, AB T0E 1E0",
			"Canada"
		]
		phone = "780-707-7129"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "deanwsmith@outlook.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10
#
#[[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 0